AWS_ACCESS_KEY = "AKIAI334JBPICZA6Z34Q"
AWS_SECRET_KEY = "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"
AWS_REGION = "eu-west-1"
#PATH_TO_PRIVATE_KEY = "/home/smiller/.ssh/id_rsa" 
#PATH_TO_PUBLIC_KEY = "/home/smiller/.ssh"  
INSTANCE_USERNAME = "ubuntu" 
